/*
 * generated by Xtext
 */
package org.typesys.xts.guidsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GuiDslRuntimeModule extends org.typesys.xts.guidsl.AbstractGuiDslRuntimeModule {

}
