/*
* generated by Xtext
*/
package org.typesys.xbase.guidsl.ui.contentassist;

import org.typesys.xbase.guidsl.ui.contentassist.AbstractXGuiDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class XGuiDslProposalProvider extends AbstractXGuiDslProposalProvider {

}
