/*
* generated by Xtext
*/
package org.typesys.xts.guidsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.typesys.xts.guidsl.services.GuiDslGrammarAccess;

public class GuiDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GuiDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.typesys.xts.guidsl.parser.antlr.internal.InternalGuiDslParser createParser(XtextTokenStream stream) {
		return new org.typesys.xts.guidsl.parser.antlr.internal.InternalGuiDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public GuiDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GuiDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
