/*
* generated by Xtext
*/
package org.typesys.xts.guidsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GuiDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/typesys/xts/guidsl/parser/antlr/internal/InternalGuiDsl.tokens");
	}
}
