/*
* generated by Xtext
*/
package org.typesys.xsem.guidsl.ui.contentassist;

import org.typesys.xsem.guidsl.ui.contentassist.AbstractXsemGuiDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class XsemGuiDslProposalProvider extends AbstractXsemGuiDslProposalProvider {

}
