def Type getType(EObject e) {
	...
	switch e {
		...
		IntLiteral: ...createIntType
		...

def Type getExpectedType(EObject e) {
    ...
	switch e {
	    ...
		Plus :	mostGeneral(e.left.type, e.right.type).mostSpecific(string)
		...		