def Type getType(EObject e) {
	...
	switch e {
		...
		IntLiteral: ...createIntType
		Plus : mostGeneral(e.left.type, e.right.type)
		...

def Type getExpectedType(EObject e) {
    ...
	switch e {
	    ...
		Plus :	mostSpecific(string, e.type)
		...		