/*
 * generated by Xtext
 */
package org.typesys.xbase.guidsl;

import org.typesys.xbase.guidsl.scoping.XGuiDslScopeProviderXbase;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XGuiDslRuntimeModule extends org.typesys.xbase.guidsl.AbstractXGuiDslRuntimeModule {
	
	public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
		return XGuiDslScopeProviderXbase.class;
	}

}
