/*
 * generated by Xtext
 */
package org.typesys.xbase.guidsl;

import org.eclipse.xtext.scoping.IScopeProvider;
import org.typesys.xbase.guidsl.scoping.XGuiDslScopeProviderXbase;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XGuiDslRuntimeModule extends org.typesys.xbase.guidsl.AbstractXGuiDslRuntimeModule {

	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return XGuiDslScopeProviderXbase.class;
	}
}
