/*
 * generated by Xtext
 */
package org.typesys.xbase.guidsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XGuiDslUiModule extends org.typesys.xbase.guidsl.ui.AbstractXGuiDslUiModule {
	public XGuiDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
