/*
 * generated by Xtext
 */
package org.typesys.xsem.guidsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XsemGuiDslUiModule extends org.typesys.xsem.guidsl.ui.AbstractXsemGuiDslUiModule {
	public XsemGuiDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
