/*
 * generated by Xtext
 */
package org.typesys.xsem.guidsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XsemGuiDslRuntimeModule extends org.typesys.xsem.guidsl.AbstractXsemGuiDslRuntimeModule {

}
