/*
* generated by Xtext
*/
package org.typesys.xsem.guidsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class XsemGuiDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
