/*
* generated by Xtext
*/
package org.typesys.xts.guidsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GuiDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.typesys.xts.guidsl.ui.internal.GuiDslActivator.getInstance().getInjector("org.typesys.xts.guidsl.GuiDsl");
	}
	
}
