/*
 * generated by Xtext
 */
package org.typesys.xts.guidsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GuiDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.typesys.xts.guidsl.ui.internal.GuiDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.typesys.xts.guidsl.ui.internal.GuiDslActivator.getInstance().getInjector("org.typesys.xts.guidsl.GuiDsl");
	}
	
}
