/*
* generated by Xtext
*/
package org.typesys.guidsl.ui.contentassist;

import org.typesys.guidsl.ui.contentassist.AbstractGuiDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GuiDslProposalProvider extends AbstractGuiDslProposalProvider {

}
