#!/usr/bin/perl

$num_args = $#ARGV + 1;
if ($num_args != 3) {
  print "This scripts reads an input file and only writes lines to the output file which are between lines with the specified pattern. There can be multiple regions. The start and end pattern of a region are the same. The lines containing the pattern are not written to the output file.\n";
  print "\nUsage: $0 input output pattern\n";
  exit;
}

$in=$ARGV[0];
$out=$ARGV[1];
$pattern = $ARGV[2];
$outEnabled = 0;

# print "Input: $in\nOutput: $out\nPattern: $pattern\n";

open FILE, $in or die $!;
open FILEOUT, ">$out" or die $!;
while (<FILE>) { 
	$line = $_;	
	if ($outEnabled) {
	 	if ($line =~ m/$pattern/) {
			$outEnabled = 0; 
		} else {
			print FILEOUT $_;  
		}
 	} else {
	 	if ($line =~ m/$pattern/) {
			$outEnabled = 1; 
		}
	}
}
close FILEOUT or die $!
