/*
 * generated by Xtext
 */
package org.typesys.guidsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GuiDslUiModule extends org.typesys.guidsl.ui.AbstractGuiDslUiModule {
	public GuiDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
